app/mytrack/controllers/album.py
from flask import *
from werkzeug import secure_filename

from ..models import *
from ..config import *
from helpers import *

album = Blueprint('album', __name__, template_folder='templates')

@album.route('/album')
def album_route():
    albumid = request.args['id']
    album = Album.query.get(albumid)

    if not can_access_album(album):
        if is_logged_in():
            error = "That album doesn't exist or you are not allowed to access it"
            return render_template('error.html', error=error)
        else:
            error = "You cannot access that album, please log in"
            next_url = request.path + '?' + request.query_string
            return redirect(url_for('login.login_route', message=error, color='red', next_url=next_url))
        
    pics = db.session.query(Photo).join(Contain).filter(Contain.albumid==albumid).order_by(Contain.sequencenum)
    captions = db.session.query(Contain).filter(Contain.albumid==albumid)

    return render_template('album.html', album=album, pics=pics, captions=captions, edit=False)

@album.route('/album/edit', methods=['GET', 'POST'])
@requires_auth
def album_edit_route():
    albumid = request.args['id']
    album = Album.query.get(albumid)
    users = User.query.filter(User.username!=session['username']).add_column('username')
    acc_users = AlbumAccess.query.filter(AlbumAccess.albumid==albumid)
    acc_users_list = []
    for acc_user in acc_users:
        acc_users_list.append(acc_user.username)
    
    if not can_access_album_edit(album):
        error = "You can't edit that album silly"
        return render_template('error.html', error=error)

    pics = db.session.query(Photo).join(Contain).filter(Contain.albumid==albumid).order_by(Contain.sequencenum)

    if request.method == 'POST' and request.form['op'] == 'add':
        file = request.files['file']
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            caption = request.form['caption']
            albumid = request.form['albumid']
            filename = add_pic(filename, albumid, caption)
            file.save(UPLOAD_FOLDER + filename)
    elif request.method == 'POST' and request.form['op'] == 'delete':
        picid = request.form['picid']
        delete_pic(picid, albumid)

    elif request.method == 'POST' and request.form['op'] == 'update':
        new_acc_users = []
        for user in users:
            if user.username in request.form:
                new_acc_users.append(user.username)
        update_album(albumid, request.form['title'], request.form['access'], new_acc_users)
        return redirect(url_for('album.album_route', id=albumid))

    return render_template('album.html', album=album, pics=pics, users=users, acc_users_list=acc_users_list, edit=True)

app/mytrack/controllers/albums.py
from flask import *

from ..models import *
from helpers import *

albums = Blueprint('albums', __name__, template_folder='templates')

@albums.route('/albums')
@requires_auth
def albums_route():
    username = request.args['username']

    if not can_access_albums(username):
        if is_logged_in():
            error = "You cannot access those albums"
            return render_template('error.html', error=error)
        else:
            error = "You cannot access those albums, please log in"
            next_url = request.path + '?' + request.query_string
            return redirect(url_for('login.login_route', message=error, color='red', next_url=next_url))

    useralbums = Album.query.filter(Album.username==username)
    return render_template('albums.html', useralbums=useralbums, edit=False, username=username)

@albums.route('/albums/edit', methods=['GET', 'POST'])
@requires_auth
def albums_edit_route():
    username = request.args['username']

    if not can_access_albums(username):
        error = "You cannot edit those albums"
        return render_template('error.html', error=error)
    
    useralbums = Album.query.filter(Album.username==username)
    if request.method == 'POST' and request.form['op'] == 'add':
        title = request.form['title']
        username = request.form['username']
        add_album(title, username)
    elif request.method == 'POST' and request.form['op'] == 'delete':
        albumid = request.form['albumid']
        delete_album(albumid)

    return render_template('albums.html', useralbums=useralbums, edit=True, username=username)

app/mytrack/controllers/login.py
from flask import *

from ..models import *
from ..config import *
from helpers import *
import mail

login = Blueprint('login', __name__, template_folder='templates')

@login.route('/login', methods=['GET', 'POST'])
def login_route():
    message = None
    color = None
    if 'message' in request.args:
        message = request.args['message']
        color = request.args['color']

    if request.method == 'GET':
        return render_template('login.html', message=message, color=color)
        
    if request.method == 'POST':
        username = request.form['username']
        error = ''
        if check_login(username, request.form['password']):
            if not check_active(username):
                error = 'Account not yet activated, check your email'
            else:
                session['username'] = username
                if 'next_url' in request.args:
                    # Go back to page user was trying to access
                    return redirect(request.args['next_url'])
                return redirect(url_for('index.index_route'))
        else:
            error = "Incorrect username or password"
            
        return render_template('login.html', message=error, color='red')

@login.route('/login/forgot', methods=['GET', 'POST'])
def forgot_pass_route():
    message = None
    color = None
    if 'message' in request.args:
        message = request.args['message']
        color = request.args['color']

    if request.method == 'GET':
        return render_template('forgot_pass.html', message=message, color=color)

    if request.method == 'POST':
        username = request.form['username']
        user = User.query.get(username)
        if user != None:
            new_password = generate_new_pass()
            update_user(username, user.firstname, user.lastname, new_password, user.email)
            if SEND_EMAILS:
                mail.send_new_password(user, new_password)

    message = "If user exists, an email has been sent with a new password"
    return redirect(url_for('login.login_route', message=message, color='green'))

app/mytrack/controllers/pic.py
from flask import *

from ..models import *
from helpers import *

pic = Blueprint('pic', __name__, template_folder='templates')

@pic.route('/pic')
def pic_route():
    picid = request.args['id']
    pic = Photo.query.get(picid)
    # Check that pic is valid
    if pic == None:
        error = "That picture doesn't exist"
        return render_template('error.html', error=error)

    albumid = (Contain.query.filter(Contain.picid==picid).first()).albumid
    album = Album.query.get(albumid)

    if not can_access_album(album):
        if is_logged_in():
            error = "You cannot access that picture"
            return render_template('error.html', error=error)
        else:
            error = "You cannot access that picture, please log in"
            next_url = request.path + '?' + request.query_string
            return redirect(url_for('login.login_route', message=error, color='red', next_url=next_url))

    near_pics = find_near_pics(album.albumid, picid)
    prevpic = near_pics[0]
    nextpic = near_pics[1]
    
    caption = (Contain.query.filter(Contain.picid==picid).first()).caption

    return render_template('pic.html', pic=pic, caption=caption, album=album, prevpic=prevpic, nextpic=nextpic)

app/mytrack/controllers/search.py
from flask import *
import requests

from ..models import *
from ..config import *
from helpers import *
import mail

search = Blueprint('search', __name__, template_folder='templates')

@search.route('/search', methods=['GET', 'POST'])
def search_route():
    message = None
    color = None
    query = None
    if 'id' in request.args:
        picid = request.args['id'];
        query = (Contain.query.filter(Contain.picid==picid).first()).caption
        print query
    if 'message' in request.args:
        message = request.args['message']
        color = request.args['color']

    if request.method == 'POST':
        query = request.form['query']
        print 'you searched for: ' + query
        
    result = requests.get('http://%s:6078/search?q=%s' 
    						%(SERVER_NAME, query))
    # print result.text
    pics = []
    pics_info = result.json()
    for pic_info in pics_info['hits']:
    	pics.append(Photo.query.get(pic_info['id']))

    albumid = (Album.query.filter(Album.title=='search')).first().albumid
    captions = db.session.query(Contain).filter(Contain.albumid==albumid)

    return render_template('search.html', pics=pics, captions=captions, message=None, color=None)

app/mytrack/controllers/user.py
from flask import *

from ..models import *
from ..config import *
from helpers import *

user = Blueprint('user', __name__, template_folder='templates')

@user.route('/user', methods=['GET', 'POST'])
def user_route():
    if is_logged_in():
        return redirect(url_for('user.user_edit_route'))

    message = None
    color = None
    if 'message' in request.args:
        message = request.args['message']
        color = request.args['color']

    if request.method == 'POST':   
        if check_unique_username(request.form['username']):
            if check_passwords_match(request.form['password1'], request.form['password2']):
                print "match"
            add_user(request.form['username'], request.form['firstname'], request.form['lastname'], request.form['password1'], request.form['email'])
            message = "Account created successfully, check your email to activate your account."
            return redirect(url_for('index.index_route', message=message, color='green'))
        else:    
            message = "Username is unavailable. Please select a unique username."
            return redirect(url_for('user.user_route', message=message, color='red'))
    
    return render_template('new_user.html', message=message, color=color)

@user.route('/user/edit', methods=['GET', 'POST'])
@requires_auth
def user_edit_route():
    user = get_cur_user()
    message = None
    color = None
    if 'message' in request.args:
        message = request.args['message']
        color = request.args['color']

    if request.method == 'GET':
        return render_template('edit_user.html', user=user, message=message, color=color)

    elif request.method == 'POST':
        if check_login(user.username, request.form['cur_password']):
            if check_passwords_match(request.form['new_password1'], request.form['new_password2']):
                print "Update Password"
                update_user(user.username, request.form['firstname'], request.form['lastname'], request.form['new_password1'], request.form['email'])
                message = "Account updated successfully"
                return redirect(url_for('user.user_edit_route', message=message, color='green'))
            else:
                print "Current Password"
                update_user(user.username, request.form['firstname'], request.form['lastname'], request.form['cur_password'], request.form['email'])
                message = "Account updated successfully"
                return redirect(url_for('user.user_edit_route', message=message, color='green'))
        else:
            message = "Incorrect account password."
            return redirect(url_for('user.user_edit_route', message=message, color='red'))

@user.route('/user/delete', methods=['POST'])
def user_delete_route():
    delete_user(session['username'])
    return redirect(url_for('logout.logout_route'))

@user.route('/user/activate/<payload>')
def user_activate_route(payload):
    message = None
    color = None
    if 'message' in request.args:
        message = request.args['message']
        color = request.args['color']

    s = get_activation_serializer()
    try:
        username = s.loads(payload)
    except BadSignature:
        abort(404)

    activate_user(username)
    session['username'] = username

    message = "Account successfully activated!"
    color = 'green'

    return redirect(url_for('index.index_route', message=message, color=color))

app/mytrack/templates/album.html
{% extends "base.html" %}
{% block content %}
  <br><br><br>
  <div class="page-header">
    {% if not edit %}
      <h1> {{ album.title }} </h1>
      <h3> By: {{ album.username }} <br>
            Access: {{ album.access }} <br>
            Created: {{ album.created }} <br>
            Last Updated: {{ album.lastupdated }}</h3>
    {% else %}
      <form action="" method="post">
        <input type="hidden" name="op" value="update">
        <button type="submit" class="btn btn-lg btn-info">Save Changes</button>
        <br>
        <br>
        <input type="text" name="title" placeholder="Title" value="{{ album.title }}"><br>
        <input type="radio" name="access" value="public" class="trigger"
          {% if album.access=='public' %} 
            checked="checked"
          {%endif%}
          > Public<br>
        <input id="priv_radio" type="radio" name="access" value="private" class="trigger" 
          {% if album.access=='private' %} 
            checked="checked"
          {%endif%}
          > Private<br> 
            <div id="p_access">
            Users allowed to access:<br>
            {% for user in users %}
              <input type="checkbox" name="{{ user.username }}"
              {% if user.username in acc_users_list %}
                checked="checked"
              {% endif %}
              >
                {{ user.username }} <br>
            {% endfor %}
            </div>
            <script>
              function displayPrivate() {
                  if($('#priv_radio').is(":checked")) {
                    $('#p_access').show();
                  }
                  else {
                    $('#p_access').hide();
                  }
              }
              $(displayPrivate)
              $('.trigger').click(displayPrivate)
            </script>
      </form>
      <h3> Add a new photo </h3>
      <form action="" method="post" enctype="multipart/form-data">
        <input type="hidden" name="op" value="add">
        <input type="hidden" name="albumid" value="{{ album.albumid }}">
        <input type="file" name="file">
        <br>
        <input type="text" name="caption" placeholder="Caption">
        <button type="submit" class="btn btn-md btn-success">Upload</button>
      </form>
    {% endif %}
    
  </div>
  {% if album.username == session['username'] and not edit %} <!-- Only show back button if viewer is owner -->
  <div class="row">
    <div class="col-md-1">
      <form method="get" action="{{ url_for('albums.albums_route') }}">
        <input type="hidden" name="username" value="{{ album.username }}">
        <button type="submit" class="btn btn-lg btn-info">Back</button>
      </form>
    </div>
  {% endif %}
  {% if album.username == session['username'] %} <!-- Only show edit button if viewer is owner -->
    {% if not edit %}
    <div class="col-md-1">
      <form method="get" action="{{ url_for('album.album_edit_route') }}">
        <input type="hidden" name="id" value="{{ album.albumid }}">
        <button type="submit" class="btn btn-lg btn-warning">Edit Album</button>
      </form>
    </div> 
  </div>
    {% endif %}
  {% endif %}
  
  <br>

    {% for pic in pics %}
    {% if loop.first or loop.index % 4 == 0 %}
      <div class="row">
    {% endif %}
      <div class="col-xs-3">
        {% if not edit %}
        <div class="thumbnail">
          <a href="{{ url_for('pic.pic_route', id=pic.picid) }}">
            <img src="{{ pic.url }}" class="img-responsive thumbnail" height="200" width="200">
          </a>
          <div class="caption">
            {% for caption in captions %}
            {% if caption.picid == pic.picid %}
            <p class="text-center" style="font-size:16px">{{caption.caption}}</p>
            {% endif %}
            {% endfor %}
            <p class="text-center" style="font-weight:300">{{pic.date}}</p>
          </div>
        </div>
        {% else %}
        <div class="thumbnail" id="delete_thumbnail">
          <a href="{{ url_for('pic.pic_route', id=pic.picid) }}">
            <img src="{{ pic.url }}" class="img-responsive thumbnail" height="200" width="200">
          </a>
          <div class="caption" id="delete_pic">
            <form method="post" action="{{ url_for('album.album_edit_route', id=album.albumid) }}">
              <input type="hidden" name="op" value="delete">
              <input type="hidden" name="albumid" value="{{ album.albumid }}">
              <input type="hidden" name="picid" value="{{ pic.picid }}">
              <button type="submit" class="btn btn-sm btn-danger" id="delete_pic_button"><span class="glyphicon glyphicon-remove">  Delete</span></button>
            </form>
          </div>
        </div>
        {% endif %}
      </div>
    {% if loop.last or loop.index % 4 == 0 %}
      </div>
      <br><br>
    {% endif %}
    {% endfor %}
  <br>
  

{% endblock %}

app/mytrack/templates/albums.html
{% extends "base.html" %}
{% block content %}


<br><br><br><br>

<div class="page-header">
  <h1><span style="font-weight:300">{{ username }}'s</span> Albums</h1>
</div>

<div class="row">
  <span class="col-md-3"></span>
  <div class="col-md-6">
    <table class="table">
      <tbody>
        {% for album in useralbums %}
          <tr id="album_list_item">
            <td style="vertical-align:middle">
              <a href="{{ url_for('album.album_route', id=album.albumid) }}">
                <h3 class="text-center">{{ album.title }}</h3>
              </a>
            </td>
            {% if edit %}
            <td style="vertical-align:middle">
              <h4>
              {% if album.access == 'public' %}
                Public
              {% else %}
                Private
              {% endif %}
              </h4>
            </td>
            <td>
              <form method="get" action="{{ url_for('album.album_edit_route') }}">
                <input type="hidden" name="id" value="{{album.albumid}}">
                <button type="submit" class="btn btn-lg btn-warning">Edit
                </button>
              </form>
            </td>
            <td>
              <form method="post" action="{{ url_for('albums.albums_edit_route', username=username) }}">
                <input type="hidden" name="op" value="delete">
                <input type="hidden" name="albumid" value="{{album.albumid}}">
                <button type="submit" class="btn btn-lg btn-danger">Delete
                </button>
              </form>
            </td>
           {% endif %}
          </tr>
        {% endfor %}
        {% if edit %}
        <tr>
          <form action="" method="post">
            <input type="hidden" name="username" value="{{username}}">
            <input type="hidden" name="op" value="add">
            <td colspan="2">
              <input type="text" required name="title" class="form-control" placeholder="Album Title">
            </td>
            <td>
              <button type="submit" class="btn btn-lg btn-success">Add</button>
            </td>
          </form>
            
        </tr>
        {% endif %}
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-1">
    {% if not edit %}
    <form method="get" action="{{ url_for('index.index_route') }}">
      <button type="submit" class="btn btn-lg btn-info">Back</button>
    </form>
  </div>
    <div class="col-md-1 pull-right">
      <form method="get" action="{{ url_for('albums.albums_edit_route') }}">
        <input type="hidden" name="username" value="{{username}}">
        <button type="submit" class="btn btn-lg btn-warning">Edit Albums</button>
      </form>
    </div>
    {% else %}
      <form method="get" action="{{ url_for('albums.albums_route') }}">
        <input type="hidden" name="username" value="{{username}}">
        <button type="submit" class="btn btn-lg btn-info">Done</button>
      </form>
  </div>
    {% endif %}
</div>
{% endblock %}

app/mytrack/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">

<head>
  <link rel="shortcut icon" href="/static/img/favicon.ico">
  <link href="/static/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/css/bootstrap-theme.min.css" rel="stylesheet">
   <link href="/static/css/custom.css" rel="stylesheet">
   <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700' rel='stylesheet' type='text/css'>
  <script src="/static/js/jquery-1.11.1.min.js"></script>
  <script src="/static/js/bootstrap.min.js"></script>
  <script src="/static/js/form.js"></script>
  <script type="text/javascript">
    function password_validator(form)
    {
      if(form.password1.value!=form.password2.value)
      {
        alert("Passwords don't match!");
        form.password1.value="";
        form.password2.value="";
        form.password1.focus();
        return false;
      }
      else
      {
        return true;
      }
    }
  </script>

  <title>AlbumMaster</title>
</head>

<body>
  <div id="body2">
  <div class="wrapper">
  {% block nav %}
  <!-- Fixed navbar -->
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{ url_for('index.index_route') }}"><b>AlbumMaster</b></a>
      </div>

      {% block navbar %}
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="{{ url_for('index.index_route') }}">Home</a></li>
          <li><a href="{{ url_for('search.search_route') }}">Search</a></li>
          {% if "username" in session %}
          <li><a href="{{ url_for('albums.albums_route', username=session['username']) }}">My Albums</a></li>
          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if "username" in session %} <!-- User is logged in -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span><span class="profile-name">&nbsp;{{ session['username'] }}</span></b></a>
              <ul class="dropdown-menu">
                <li><a href="{{ url_for('user.user_edit_route') }}">Edit Account</a></li>
                <li><a href="{{ url_for('logout.logout_route') }}">Logout</a></li>
              </ul>
          </li>
          {% else %}
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span><span class="profile-name">&nbsp;Login</span></b></a>
              <ul class="dropdown-menu">
                <li><a href="{{ url_for('login.login_route') }}">Login as <b>Existing User</b></a></li>
                <li><a href="{{ url_for('user.user_route') }}">Create a <b>New Account</b></a></li>
              </ul>
          </li>
          {% endif %}
        </ul>
      </div><!--/.nav-collapse -->
      {% endblock %}

    </div>
  </div>
  {% endblock %}

  <div class="container theme-showcase" role="main">
    {% block content %}
    
    {% endblock %}

  </div>
<div class="push">
</div>
</div> <!-- wrapper div -->
<footer>
  <div class="container">
    <p class="text-muted" align="right">
      AlbumMaster Courtesy of The Pink Fairy Armadillos<br>
      © 2014
    </p>
  </div>
</footer>
</div> <!-- body2 div -->
</body>

</html>

app/mytrack/templates/edit_user.html
{% extends "base.html" %}
{% block content %}

	<br><br><br><br>
	<h2>Edit account details</h2>
  {% if message != None %}
    {% if color == 'green' %}
    <div class="alert alert-success alert-dismissible" role="alert">
    {% elif color == 'red' %}
    <div class="alert alert-danger alert-dismissible" role="alert">
    {% endif %}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      {{ message }}
    </div>
  {% endif %}
  <form action="" method="post" onsubmit="return password_validator(this);">
    <p>
      <input type="text" name="firstname" required placeholder="First Name" value="{{user.firstname}}">
    <p>
      <input type="text" name="lastname" required placeholder="Last Name" value="{{user.lastname}}">
    <p>
      <input type="text" name="email" required placeholder="Email" value="{{user.email}}">
    <p>
      <input type="password" required name="cur_password" placeholder="Current Password" >
    <p>
      <input type="password" 
      pattern="(?=.*[a-zA-Z])(?=.*[0-9])[a-zA-Z0-9'_']{5,15}" title="Password must be at least five characters and at most fifteen character, and must include one digit and one letter. A password can contain only letters, digits and underscores"
      name="new_password1" placeholder="New Password" id="password1">
    <p>
      <input type="password" 
      pattern="(?=.*[a-zA-Z])(?=.*[0-9])[a-zA-Z0-9'_']{5,15}" title="Password must be at least five characters and at most fifteen character, and must include one digit and one letter. A password can contain only letters, digits and underscores"
      name="new_password2" placeholder="Repeat New Password" id="password2">
    <p><input type="submit" value="Save Changes">
  </form>
  <br>
  <form method="post" action="{{ url_for('user.user_delete_route') }}">
    <button type="submit" class="btn btn-lg btn-danger">Delete Account</button>
  </form>

{% endblock %}

app/mytrack/templates/error.html
{% extends "base.html" %}
{% block content %}
	<br><br><br><br>
	<h2> {{ error }} </h2>

{% endblock %}

app/mytrack/templates/forgot_pass.html
{% extends "base.html" %}
{% block content %}
  <br><br><br><br>
  <form action="" method="post">
    <p><input type="text" name="username" placeholder="Username">
    <p><input type="submit" value="Send New Password">
  </form>
{% endblock %}

app/mytrack/templates/login.html
{% extends "base.html" %}
{% block content %}
  <br><br><br><br>
  {% if message != None %}
    {% if color == 'green' %}
    <div class="alert alert-success alert-dismissible" role="alert">
    {% elif color == 'red' %}
    <div class="alert alert-danger alert-dismissible" role="alert">
    {% endif %}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      {{ message }}
    </div>
  {% endif %}
  <form action="" method="post">
    <p><input type="text" name="username" placeholder="Username">
    <p><input type="password" name="password" placeholder="Password">
    <br><br><a href="{{ url_for('login.forgot_pass_route') }}">Forgot your password? </a>
    <p><input type="submit" value="Login">
  </form>
{% endblock %}

app/mytrack/templates/pic.html
{% extends "base.html" %}
{% block content %} 
  <br><br><br><br>

  <form method="get" action="{{ url_for('album.album_route') }}">
    <input type="hidden" name="id" value="{{ album.albumid }}">
    <button type="submit" class="btn btn-lg btn-info">&lt;&lt; Back to album</button>
  </form>
  <br>
  <br>
  <img src="{{ pic.url }}" class="img-responsive center-block" id="fullscreen_pic">
  <br>
  <div class="text-center">
    <h4 id="caption">{{ caption }}</h4>
  </div>
  <br>
  <br>
  <ul class="pager">
    <li class="previous">
      <form method="get" action="{{ url_for('pic.pic_route') }}">
        <input type="hidden" name="id" value="{{ prevpic }}">
        <button type="submit" class="btn btn-lg btn-info pull-left">&larr; Previous</button>
      </form>
    </li>
    <li class="next">
      <form method="get" action="{{ url_for('pic.pic_route') }}">
        <input type="hidden" name="id" value="{{ nextpic }}">
        <button type="submit" class="btn btn-lg btn-info pull-right">Next &rarr;</button>
      </form>
    </li>
  </ul>
{% endblock %}

app/mytrack/templates/public_index.html
{% extends "base.html" %}
{% block content %}
	<br><br><br><br>
  {% if message != None %}
    {% if color == 'green' %}
    <div class="alert alert-success alert-dismissible" role="alert">
    {% elif color == 'red' %}
    <div class="alert alert-danger alert-dismissible" role="alert">
    {% endif %}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      {{ message }}
    </div>
  {% endif %}
 
    <div align="center" class="jumbotron">
        <h1>Welcome</h1>
        <p>AlbumMaster is a simple and easy to use web application which allows you to upload photos and share them with your friends.  Log in, create a new account, or browse the public albums listed below.</p>

    </div>
    <div align="center">
    	<div class="col-sm-12">
          <div class="list-group">
            <a class="list-group-item active">
              <h2>Public Albums</h2>
            </a>
	        	{% for album in public_albums %}
	        	 <a href="{{ url_for('album.album_route', id=album.albumid) }}" class="list-group-item"> <h2> <b>{{ album.title }}</b> by {{ album.username }} </h2></a>
	        	
	        	{% endfor %}
          </div>
        </div><!-- /.col-sm-4 -->
    
    </div>

   
{% endblock %}

app/mytrack/templates/search.html
{% extends "base.html" %}
{% block content %}
  <br><br><br><br>
  {% if message != None %}
    {% if color == 'green' %}
    <div class="alert alert-success alert-dismissible" role="alert">
    {% elif color == 'red' %}
    <div class="alert alert-danger alert-dismissible" role="alert">
    {% endif %}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      {{ message }}
    </div>
  {% endif %}
  <div class="row">
    <div class="col-lg-6">
      <div class="input-group">
        <form method="post" action="">
          <input type="text" name="query" class="form-control" placeholder="Search for an image">
          <input type="submit" value="Search">
        </form>
      </div><!-- /input-group -->
    </div><!-- /.col-lg-6 -->
  </div>
  <br>
  {% for pic in pics %}
    {% if loop.first or loop.index % 4 == 0 %}
      <div class="row">
    {% endif %}
      <div class="col-xs-3">
        <div class="thumbnail">
          <a href="{{ url_for('search.search_route', id=pic.picid) }}">
            <img src="{{ pic.url }}" class="img-responsive thumbnail" height="200" width="200">
          </a>
          <div class="caption">
            {% for caption in captions %}
            {% if caption.picid == pic.picid %}
            <p class="text-center" style="font-size:16px">{{caption.caption}}</p>
            {% endif %}
            {% endfor %}
            <p class="text-center" style="font-weight:300">{{pic.date}}</p>
          </div>
        </div>
      </div>
    {% if loop.last or loop.index % 4 == 0 %}
      </div>
      <br><br>
    {% endif %}
    {% endfor %}
{% endblock %}